### ISSUE TITLE
Towards 0.5.5

### ISSUE THREAD

**Issue by ablaom** [alan-turing-institute/MLJModels.jl#115]
- [x] (**Enhancement**) Dramatically speedup of @load on second call ([MLJ #280](https://github.com/alan-turing-institute/MLJ.jl/issues/280), #110, #112, PR #113, PR #114)

- [x] (**New model**) Added BayesianLDA (#108, PR #113)

- [x] (**Testing**) Added `check_registry()` for administrators to check all models in registry are `@load`-able. To be used after each `@update` (PR #113, PR #114)
