### ISSUE TITLE
Towards 0.5.8

### ISSUE THREAD

**Issue by ablaom** [alan-turing-institute/MLJModels.jl#144]
- [x] (**Enhancement**) Improve `Stadardizer` checks (#95)

- [x] (**Enhancement**) Add `new_features` to `OneHotEncoder` report (PR #147, [MLJ #357](https://github.com/alan-turing-institute/MLJ.jl/issues/357))

- [x] (**Enhancement**) Allow more general objective functions in `XGBoostRegressor` (#145)

- [x] (**Enhancement**) Allow `DecisionTree` models to accept any ordinal feature -  specifically tables with any `Continuous`, `Count` or `OrderedFactor` columns (#134)

- [x] (**Enhancement**) Add `print_tree` method to the report of DecisionTreeClassifier (https://github.com/alan-turing-institute/MLJ.jl/issues/347)
