### ISSUE TITLE
Towards 0.5.3

### ISSUE THREAD

**Issue by ablaom** [alan-turing-institute/MLJModels.jl#83]
- [x] (**Enhancement**) Add `UnivariateDiscretizer` for discretizing continuous data (PR #75) 

**Additions**

- [x] (**new interface**) LDA from MultivariateStats optionally  with robust covariance estimation (thanks to Sam Okon, PR #89; +  fixes #99)
- [x] (**new model**) added MLJLinearModels to the registry (#102) 

**Code improvements**

- [x]  (**enhancement**) more use of `@mlj_model` and `metadata_*` which should  help long-term maintenance; use of description strings for models. (#99)

**Comment by tlienart** [comment]
patch release PR #106

**Comment by tlienart** [comment]
@JuliaRegistrator register

Release notes:

- [x] (**Enhancement**) Add `UnivariateDiscretizer` for discretizing continuous data (PR #75) 
- [x] (**new interface**) LDA from MultivariateStats optionally  with robust covariance estimation (thanks to Sam Okon, PR #89; +  fixes #99)
- [x] (**new models**) added MLJLinearModels to the registry (#102) 

**Code improvements**

- [x]  (**enhancement**) more use of `@mlj_model` and `metadata_*` which should  help long-term maintenance; use of description strings for models. (#99)
